language: bash
services: docker

install:
  - make docker-build

after_success:
  # Log that the build worked, because we all need some good news
  - echo "Success running lightning-integration"

jobs:
  include:

    - name: 'Build eclair'
      script:
        - docker run lnintegration bash -c "make update-eclair bin/eclair.jar && py.test -v test.py -k EclairNode"

    - name: 'Build clightning'
      script:
        - docker run lnintegration bash -c "make update-clightning bin/lightningd && py.test -v test.py -k LightningNode"

    - name: 'Build lnd'
      script:
        - docker run lnintegration bash -c "make update-lnd bin/lnd && py.test -v test.py -k LndNode"

    - name: 'Build ptarmigan'
      script:
        - docker run lnintegration bash -c "make update-ptarmigan bin/ptarmd && py.test -v test.py -k PtarmNode"

    - name: 'Build rust-lightning-bitcoinrpc'
      script:
        - docker run lnintegration bash -c "make update-rust-lightning bin/rust-lightning-bitcoinrpc && py.test -v test.py -k RustLightningBitcoinrpcNode"
